apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 2da22245-4a32-469d-977c-efa2a5592aba
    subject: custom_litmus
    workflow_id: 31cdace4-b130-4cbd-a093-5faeee01b4ae
    workflows.argoproj.io/controller-instanceid: 2da22245-4a32-469d-977c-efa2a5592aba
  name: custom-1697191666
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-memory-hog-tek
        template: pod-memory-hog-tek
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - container:
      args:
      - kubectl apply -f /tmp/pod-memory-hog-tek.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.14.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-memory-hog-tek
        path: /tmp/pod-memory-hog-tek.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Injects memory consumption on pods belonging to an app deployment
            kind: ChaosExperiment
            metadata:
              name: pod-memory-hog
              labels:
                name: pod-memory-hog
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.14.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:2.14.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-memory-hog
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: MEMORY_CONSUMPTION
                    value: "500"
                  - name: NUMBER_OF_WORKERS
                    value: "1"
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: LIB_IMAGE
                    value: litmuschaos/go-runner:2.14.0
                  - name: STRESS_IMAGE
                    value: alexeiled/stress-ng:latest-ubuntu
                  - name: CONTAINER_RUNTIME
                    value: docker
                  - name: SOCKET_PATH
                    value: /var/run/docker.sock
                  - name: SEQUENCE
                    value: parallel
                  - name: TARGET_PODS
                    value: ""
                  - name: NODE_LABEL
                    value: ""
                labels:
                  name: pod-memory-hog
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/runtime-api-usage: "true"
                  app.kubernetes.io/version: 2.14.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-memory-hog-tek.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.14.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-memory-hog-tek
        path: /tmp/chaosengine-pod-memory-hog-tek.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-memory-hog-tek
              labels:
                workflow_run_id: "{{workflow.uid}}"
            spec:
              engineState: active
              appinfo:
                appns: io
                applabel: app=api-gateway
                appkind: deployment
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-memory-hog
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: MEMORY_CONSUMPTION
                          value: "500"
                        - name: PODS_AFFECTED_PERC
                          value: "100"
                        - name: CONTAINER_RUNTIME
                          value: docker
                        - name: SOCKET_PATH
                          value: /var/run/docker.sock
                    probe: []
    metadata:
      labels:
        weight: "10"
    name: pod-memory-hog-tek
    outputs: {}
  - container:
      args:
      - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.14.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
